title: Derrick's FrontEnd Experience
author: Derrick Pine
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Derrick Pine, HTML, CSS, GitHub, FreeCodeCamp

# social links
twitter_username: @dpine44
github_username:  derrickpine

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
